/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../pages/__root";
import { Route as LayoutRouteRouteImport } from "./../pages/_layout/route";
import { Route as LayoutIndexRouteImport } from "./../pages/_layout/index";
import { Route as CommonLoginRouteImport } from "./../pages/_common/login";

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const CommonLoginRoute = CommonLoginRouteImport.update({
  id: "/_common/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof LayoutIndexRoute;
  "/login": typeof CommonLoginRoute;
}
export interface FileRoutesByTo {
  "/login": typeof CommonLoginRoute;
  "/": typeof LayoutIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_layout": typeof LayoutRouteRouteWithChildren;
  "/_common/login": typeof CommonLoginRoute;
  "/_layout/": typeof LayoutIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login";
  fileRoutesByTo: FileRoutesByTo;
  to: "/login" | "/";
  id: "__root__" | "/_layout" | "/_common/login" | "/_layout/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren;
  CommonLoginRoute: typeof CommonLoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof LayoutRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_layout/": {
      id: "/_layout/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof LayoutIndexRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_common/login": {
      id: "/_common/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof CommonLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface LayoutRouteRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute;
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
};

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  CommonLoginRoute: CommonLoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
